#!/usr/bin/env node
// Packs the recorded MP3 clips into src/game/voicebank-data.js, keyed the way
// the dialogue director looks lines up at runtime (`who|clauseText`).

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

async function main() {
  const manifest = JSON.parse(
    await readFile(resolve(ROOT, 'tools/voice-manifest.json'), 'utf8')
  );
  const entries = [];
  let bytes = 0;
  for (let i = 0; i < manifest.length; i += 1) {
    const clip = manifest[i];
    const path = resolve(ROOT, 'tools/voices', `${String(i).padStart(3, '0')}.mp3`);
    // eslint-disable-next-line no-await-in-loop
    const data = await readFile(path);
    bytes += data.length;
    const key = `${clip.who}|${clip.text}`.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    entries.push(`'${key}':'${data.toString('base64')}'`);
  }
  const source = `// Generated by tools/pack-voices.mjs — do not edit by hand.
// ${manifest.length} neural-TTS dialogue clips (MP3, 24 kHz mono), keyed by
// \`who|clauseText\` exactly as the dialogue director looks them up.
export const VOICE_DATA = {
${entries.join(',\n')}
};
`;
  await writeFile(resolve(ROOT, 'src/game/voicebank-data.js'), source, 'utf8');
  console.log(`packed ${manifest.length} clips, ${(bytes / 1024 / 1024).toFixed(1)} MB audio -> voicebank-data.js`);
}

main().catch((err) => { console.error(err); process.exit(1); });
